title: Aizelmarie Magsino
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst with a Bachelor’s degree in Biology and Minor in Cognitive Science from Lehigh University and a Certificate in Data Science & Visualization from Rutgers University’s Data Science Bootcamp
  <br><br>
  <a href="https://www.linkedin.com/in/aizelmarie-magsino/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-156062675-1 # your Google Analytics tracking ID here
